namespace: reverse-words-njiratti-stage
namePrefix: dev-
commonLabels:
  app: reversewords-dev-app
resources:
- base/namespace.yaml
- base/deployment.yaml
- base/service.yaml
- base/route.yaml
patchesStrategicMerge:
- overlays/deployment.yaml
