apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: njiratti-dev-app
  namespace: gitops-apps
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - njiratti-dev-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: njiratti-dev-app-subscription
  namespace: gitops-apps
  labels:
    app: njiratti-dev-app
spec:
  channel: gitops-apps/njiratti-gitops-github
  placement:
    placementRef:
      kind: PlacementRule
      name: development-clusters
